"""Initial Phase 1 Accounts migration

Revision ID: d75526995b69
Revises: 
Create Date: 2026-05-25 21:03:18.970980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75526995b69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accessibility_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_input_mode', sa.String(length=50), nullable=True),
    sa.Column('font_size_scale', sa.Float(), nullable=True),
    sa.Column('high_contrast', sa.Boolean(), nullable=True),
    sa.Column('reduce_motion', sa.Boolean(), nullable=True),
    sa.Column('screen_reader_optimized', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('care_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('taker_id', sa.String(length=36), nullable=True),
    sa.Column('monitored_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_enabled', sa.Boolean(), nullable=True),
    sa.Column('checkin_time', sa.String(length=5), nullable=True),
    sa.Column('medication_enabled', sa.Boolean(), nullable=True),
    sa.Column('medication_times', sa.JSON(), nullable=True),
    sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('reminder_settings')
    op.drop_table('care_relationships')
    op.drop_table('accessibility_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
