// STRINGS DICTIONARY
export const STRINGS = {
  es: {
    idle_title: "¿Cómo te sientes hoy?",
    idle_subtitle: "Toca para hablar o elige otro método",
    questions: "Preguntas",
    aac_cards: "Tarjetas AAC",
    ready: "LISTO",
    listening: "ESCUCHANDO",
    confirm: "CONFIRMAR",
    type_message: "ESCRIBIR MENSAJE",
    error: "ERROR",
    what_we_heard: "Lo que escuchamos",
    edit_transcript: "Editar transcripción",
    your_message: "Tu mensaje",
    send_to_echovolt: "Enviar a EchoVolt",
    try_voice_again: "Intentar voz de nuevo",
    cancel: "Cancelar",
    use_aac_instead: "Usar tarjetas AAC",
    use_voice: "Usar voz",
    back: "Atrás",
    saving_transcript: "Guardando transcripción...",
    sending_to_ai: "Enviando a la IA de EchoVolt...",
    analyzing_entry: "Analizando tu mensaje...",
    building_response: "Construyendo respuesta...",
    done: "Listo",
    could_not_reach_ai: "No se pudo conectar con la IA de EchoVolt",
    make_sure_lm_studio: "Asegúrate de que LM Studio esté funcionando y accesible.",
    go_back: "Atrás",
    entry_captured: "Mensaje capturado",
    echovolt_response: "Respuesta de EchoVolt",
    crisis_hint: "Si te encuentras en una crisis, por favor contacta a los servicios de emergencia o una línea de salud mental de inmediato.",
    no_response: "No se recibió respuesta.",
    say_more: "Hablar más",
    what_you_said: "LO QUE DIJISTE",
    categories: "Categorías",
    quick_phrases: "Frases rápidas",
    core_words: "Palabras clave",
    build_message_placeholder: "Construye tu mensaje...",
    send: "ENVIAR",
    voice: "Voz",
    mic_placeholder: "Habla ahora...",
    mic_error_denied: "El acceso al micrófono fue denegado. Por favor escribe tu mensaje.",
    mic_error_no_speech: "No se detectó voz. Por favor escribe o intenta de nuevo.",
    mic_error_generic: "STT no disponible. Escribe tu mensaje abajo.",
    processing_title: "Procesando tu mensaje...",
    processing_subtitle: "EchoVolt está leyendo lo que compartiste.",
  },
  en: {
    idle_title: "How are you doing?",
    idle_subtitle: "Tap to talk, or choose another input method",
    questions: "Questions",
    aac_cards: "AAC Cards",
    ready: "READY",
    listening: "LISTENING",
    confirm: "CONFIRM",
    type_message: "TYPE MESSAGE",
    error: "ERROR",
    what_we_heard: "WHAT WE HEARD",
    edit_transcript: "Edit transcript",
    your_message: "YOUR MESSAGE",
    send_to_echovolt: "Send to EchoVolt",
    try_voice_again: "Try voice again",
    cancel: "Cancel",
    use_aac_instead: "Use AAC Cards instead",
    use_voice: "Use Voice",
    back: "Back",
    saving_transcript: "Saving transcript...",
    sending_to_ai: "Sending to EchoVolt AI...",
    analyzing_entry: "Analyzing your entry...",
    building_response: "Building response...",
    done: "Done",
    could_not_reach_ai: "Could not reach EchoVolt AI",
    make_sure_lm_studio: "Make sure LM Studio is running and reachable.",
    go_back: "Go Back",
    entry_captured: "Entry Captured",
    echovolt_response: "EchoVolt's Response",
    crisis_hint: "If you are in crisis, please contact emergency services or a mental health line immediately.",
    no_response: "No response received.",
    say_more: "Say More",
    what_you_said: "WHAT YOU SAID",
    categories: "Categories",
    quick_phrases: "Quick Phrases",
    core_words: "Core Words",
    build_message_placeholder: "Build your message...",
    send: "SEND",
    voice: "Voice",
    mic_placeholder: "Speak now...",
    mic_error_denied: "Microphone access was denied. Please type your message.",
    mic_error_no_speech: "No speech detected. Please type or try again.",
    mic_error_generic: "STT unavailable. Type your message below.",
    processing_title: "Processing your entry...",
    processing_subtitle: "EchoVolt is reading what you shared.",
  }
};

// GET STRINGS HELPER
export function getStrings(user) {
  const lang = user?.preferred_language === 'en' ? 'en' : 'es';
  return STRINGS[lang];
}
