import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity, SafeAreaView, ScrollView } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { ChevronLeft, FileText, Download, Share2 } from 'lucide-react-native';
import { T } from '@/theme';

const REPORTS = [
  { id: '1', title: 'Clinical Monthly Summary', date: 'Oct 2025', type: 'System Auto-Gen', size: '2.4 MB' },
  { id: '2', title: 'Neuro-Vocal Baseline Shift', date: 'Sep 28, 2025', type: 'AI Diagnostic', size: '1.1 MB' },
  { id: '3', title: 'Medication Adherence Audit', date: 'Sep 15, 2025', type: 'Compliance', size: '0.8 MB' },
];

export default function DrReportScreen({ navigation }) {
  return (
    <SafeAreaView style={styles.container}>
      <StatusBar style="dark" />
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <ChevronLeft size={24} color={T.n700} />
          <Text style={styles.headerTitle}>Clinical Reports</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.hero}>
          <View style={styles.iconBox}>
            <FileText size={32} color={T.primary} />
          </View>
          <Text style={styles.heroTitle}>Automated Reporting</Text>
          <Text style={styles.heroSub}>Clinically-validated documentation generated by EchoVolt Core.</Text>
        </View>

        <View style={styles.list}>
          {REPORTS.map((r, i) => (
            <View key={i} style={styles.card}>
              <View style={styles.cardMain}>
                <View style={styles.fileIcon}>
                  <FileText size={24} color={T.n400} />
                </View>
                <View style={styles.info}>
                  <Text style={styles.repTitle}>{r.title}</Text>
                  <Text style={styles.repMeta}>{r.date} • {r.type}</Text>
                </View>
              </View>
              <View style={styles.footer}>
                <Text style={styles.sizeText}>{r.size}</Text>
                <View style={styles.actions}>
                  <TouchableOpacity style={styles.actionBtn}>
                    <Share2 size={18} color={T.n500} />
                  </TouchableOpacity>
                  <TouchableOpacity style={[styles.actionBtn, styles.dlBtn]}>
                    <Download size={18} color={T.primary} />
                    <Text style={styles.dlText}>Download</Text>
                  </TouchableOpacity>
                </View>
              </View>
            </View>
          ))}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: T.n100,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: T.surf,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontFamily: T.fontSora,
    fontSize: 18,
    fontWeight: T.w8,
    color: T.n900,
  },
  content: {
    padding: 20,
  },
  hero: {
    alignItems: 'center',
    marginBottom: 32,
  },
  iconBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: T.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  heroTitle: {
    fontFamily: T.fontSora,
    fontSize: 22,
    fontWeight: T.w8,
    color: T.n900,
  },
  heroSub: {
    fontFamily: T.fontNunito,
    fontSize: 14,
    color: T.n500,
    fontWeight: T.w6,
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 40,
  },
  list: {
    gap: 16,
  },
  card: {
    backgroundColor: T.surf,
    borderRadius: 24,
    padding: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  cardMain: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  fileIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: T.n100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  info: {
    flex: 1,
  },
  repTitle: {
    fontFamily: T.fontNunito,
    fontSize: 15,
    fontWeight: T.w8,
    color: T.n900,
  },
  repMeta: {
    fontFamily: T.fontNunito,
    fontSize: 12,
    color: T.n500,
    fontWeight: T.w6,
    marginTop: 2,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: T.n100,
    paddingTop: 16,
  },
  sizeText: {
    fontFamily: T.fontNunito,
    fontSize: 12,
    fontWeight: T.w7,
    color: T.n400,
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
  },
  actionBtn: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: T.n100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dlBtn: {
    flexDirection: 'row',
    backgroundColor: T.primarySoft,
    paddingHorizontal: 16,
    gap: 8,
  },
  dlText: {
    fontFamily: T.fontNunito,
    fontSize: 13,
    fontWeight: T.w8,
    color: T.primary,
  },
});
